### ISSUE TITLE
Run executor -> executor comms via IPs rather than FQDNs

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#108]
See thread at https://github.com/apache-spark-on-k8s/spark/pull/102#issuecomment-278835039 -- it's probably more reliable in k8s to run pod to pod communication via IP instead of via hostname.  Need to make sure we don't lose much descriptiveness in Spark UIs and elsewhere by going to IPs from Hostnames though (hostnames are more familiar and memorable for debugging).

**Comment by foxish** [comment]
I'm not sure what we stand to gain by switching over to IPs. Definitely seems like something we should do in beta. WDYT?

**Comment by ash211** [comment]
We gain resiliency against flaky DNS services, though arguable if we're seeing flaky DNS we should diagnose that part of k8s separately.

**Comment by kimoonkim** [comment]
Maybe we can close this issue as well?

**Comment by ash211** [comment]
Fixed in https://github.com/apache-spark-on-k8s/spark/pull/215
