### ISSUE TITLE
Code cleanup for Kubernetes Client

### ISSUE THREAD

**Issue by mccheah** [apache-spark-on-k8s/spark#109]
`org.apache.spark.deploy.kubernetes.Client` is just over 800 lines long. Find a way to break it down into multiple classes that each handle a different aspect of submitting to Kubernetes. One aspect could be the watches and readiness, for example. Another could be configuring SSL.

**Comment by foxish** [comment]
@mccheah Do we want to do this before we cut the alpha release?

**Comment by mccheah** [comment]
Don't think so - would be a pretty significant change. Let's release what we have as the alpha (or something close to it) and we can refactor + harden it after the fact.

**Comment by foxish** [comment]
Agreed. Marking this as beta.

**Comment by mccheah** [comment]
Moving to alpha since we'd like this to get #110 into alpha as well.

**Comment by foxish** [comment]
This item is done I think
@mccheah

**Comment by mccheah** [comment]
Sort of - I'm going to close this for now, it's a little vague and we can break it down more granularly, and the different cleanups can be done over time. This has everything I eventually want though, at least from my current perspective: https://github.com/apache-spark-on-k8s/spark/pull/184
