### ISSUE TITLE
Use a separate k8s service account for driver pod vs launcher process

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#159]
I'm launching jobs into a locked down environment, and want to be able to control service accounts at a fine-grained level.

Currently we interact with the apiserver from two processes:
- SparkLauncher -- creates the driver pod and creates and deletes a service for the pod
- driver pod -- creates and deletes executor pods

I want to make sure that the account used by those two processes is independently configurable, because I want service creation to be possible from the SparkLauncher and not possible from the driver pod or executor pods.

cc @mccheah

**Comment by foxish** [comment]
@ash211 Do you think we should do this for the alpha?

**Comment by ash211** [comment]
I don't think it's a requirement for the alpha

**Comment by ash211** [comment]
Closing in favor of https://github.com/apache-spark-on-k8s/spark/issues/182 which is a better-written description of the use case
