### ISSUE TITLE
Documentation plan for alpha release

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#168]
- [x] Add prerequisites section (https://github.com/apache-spark-on-k8s/spark/pull/171)
- [x] Add instructions to find master URL (https://github.com/apache-spark-on-k8s/spark/pull/169)
- [x] Pointer to pre-built alpha docker images for driver and executor (https://github.com/apache-spark-on-k8s/spark/pull/176)
- [x] Instructions to run on public cloud infrastructure (GKE, etc) (https://github.com/apache-spark-on-k8s/spark/pull/176)
- [x] Point to alpha release tarball from within docs

The general goal is to ensure that the docs serve the following different audiences:
1. People new to k8s and spark
2. People familiar with k8s who are trying out spark integration
3. Advanced users/developers who need access to custom networking and an understanding of the system as a whole

@ash211 Please feel free to add anything you think we're missing here.

**Comment by foxish** [comment]
Closing. The documentation items for the alpha release are complete.

**Comment by tnachen** [comment]
:clap:
