### ISSUE TITLE
Turn off Travis tests now that we have Jenkins running

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#188]
As mentioned indirectly by @foxish at https://github.com/apache-spark-on-k8s/spark/pull/187#issuecomment-286939713

I'd propose now that we have the Jenkins builds up and running (thanks to great work at https://github.com/apache-spark-on-k8s/spark/issues/158#issuecomment-284074832 !) we should disable the Travis tests.  They are redundant with running the tests in Jenkins, don't include the integration tests, and seem to flake at a higher rate than the Jenkins tests.

Thoughts on turning those off now @kimoonkim @cvpatel ?

**Comment by kimoonkim** [comment]
+1. I think we can turn it off in the github admin UI. @ssuchter ?

**Comment by ssuchter** [comment]
Done!

**Comment by ash211** [comment]
Looks good, thanks!
