### ISSUE TITLE
Support SparkLauncher#NO_RESOURCE as the app resource

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#213]
https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/launcher/src/main/java/org/apache/spark/launcher/SparkLauncher.java#L76L81

**Comment by mccheah** [comment]
The issue here would be that we try to read an application resource that doesn't exist; our submission code assumes the app resource will always be provided.

**Comment by ash211** [comment]
Done in V2 -- see https://github.com/apache-spark-on-k8s/spark/blob/408c65f65c569a63508ada134139e4d5b186cd90/resource-managers/kubernetes/integration-tests/src/test/scala/org/apache/spark/deploy/kubernetes/integrationtest/KubernetesV2Suite.scala#L129
