### ISSUE TITLE
Respect JVM-wide proxy settings in the launcher

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#226]
Otherwise okhttp requests don't get proxied, so the ping loop and subsequent post of config/files/jars from submitter to driver pod's rest service don't make it out the proxy.  Apparently okhttp doesn't respect these by default.

See https://github.com/palantir/spark/compare/master...respect-http-proxy-palantir12 which we had to do to get an internal application working.

cc @mccheah

**Comment by mccheah** [comment]
I wonder if we should have a spark-specific setting for this or if we should just work off of the default system properties. My guess would be the latter to make our application consistent with the existing JVM-HTTP standards.

**Comment by ash211** [comment]
If a JVM has the proxy system properties set, the expectation I have at least is that all the http libraries in that JVM use those proxy settings.  An advanced case is to more specifically set proxy settings on a per-client basis, without modifying the entire JVM's proxy settings.  That's important for large JVMs with lots of various libraries running together, but for this proxy the submission is always in its own JVM and not running with others.  So I'm less concerned about the blunt instrument of setting the proxy on the entire JVM
