### ISSUE TITLE
Beta Plan for Spark-Kubernetes

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#232]
As per our discussion today, just formalizing the different focus areas and the people associated with each effort.
**Code Freeze: May 23**

@mccheah @ash211 
- Submission server
- Compatibility testing (with internal applications)
- Dynamic executor scaling
- Release branch

***

@ssuchter @varunkatta @kimoonkim 
- Scale test for large SparkJobs to read/write data to HDFS
- Locality optimization (HDFS/Spark)
- Executor recovery edge cases - manual tests & possibly automated ones as well
- Spark Metrics documentation (with @erikerlandson)

***

@erikerlandson 

- Verify working with OpenShift
- Tests against reference applications for Spark - investigate if it can be used in integration tests

***

@foxish

- Dynamic Executor Allocation
- ThirdPartyResources for SparkJobs
- Test plan for beta
- Release branch
- Rebasing to Spark 2.2.0 and testing

***

@tnachen 

- Documentation: "internals" doc to help folks understand how the integration works

## Other important unclaimed items:

- Custom Executor and Driver Pod YAMLs
- Custom images and documentation around that

**Comment by foxish** [comment]
cc @iyanuobidele 
Thanks for taking on TPR support again.

**Comment by ash211** [comment]
@foxish probably can close this issue now that the release off the 2.2.0 branch is out?
