### ISSUE TITLE
Support reading apiserver PEM CA from driver pod's image

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#233]
`spark.kubernetes.authenticate.driver.caCertFile` should support URIs of the form `local://` that refer to files in the driver pod's image.

The background here is that we have an internal application running an init container for the driver pod that populates the apiserver CA PEM file into the docker image, and need to be able to use the apiserver PEM that is placed into the pod by that init container.

**Comment by mccheah** [comment]
It's probably easier if this would only be implemented for submission V2. There might be a way to write it in a way that's shared between both V1 and V2 but isolation to just V2 is preferred.

**Comment by mccheah** [comment]
This is doable now but it requires setting `spark.kubernetes.authenticate.driver.mounted.caCertFile` which we don't document externally. The idea is that this value is usually set by the submission client when it mounts the CA certificate as a Kubernetes secret, but if the value is provided by the user in specific scenarios then the submission client doesn't mount the secret and uses the provided value directly.

I think the API here can be revisited but this is fine for now.
