### ISSUE TITLE
Build failure on tag v2.1.0-kubernetes-0.1.0-alpha.2

### ISSUE THREAD

**Issue by erikerlandson** [apache-spark-on-k8s/spark#250]
Trying to build checkout of tag `v2.1.0-kubernetes-0.1.0-alpha.2`

Per the standard [instructions](https://github.com/apache-spark-on-k8s/spark/blob/v2.1.0-kubernetes-0.1.0-alpha.2/resource-managers/kubernetes/README.md#building-spark-with-kubernetes-support), I issued the build commands
```
% cd /path/to/spark
% build/mvn clean
% build/mvn compile -Pkubernetes -pl resource-managers/kubernetes/core -am -DskipTests
```

Build failed fairly fast while trying to find artifact `org.apache.spark:spark-network-common_2.11:jar:tests:2.1.0-k8s-0.1.0-SNAPSHOT`

Full error output:
```
[INFO] Reactor Summary:
[INFO] 
[INFO] Spark Project Parent POM ........................... SUCCESS [  1.319 s]
[INFO] Spark Project Tags ................................. SUCCESS [  1.749 s]
[INFO] Spark Project Networking ........................... SUCCESS [  2.551 s]
[INFO] Spark Project Shuffle Streaming Service ............ FAILURE [01:10 min]
[INFO] Spark Project Unsafe ............................... SKIPPED
[INFO] Spark Project Launcher ............................. SKIPPED
[INFO] Spark Project Core ................................. SKIPPED
[INFO] Spark Project Kubernetes ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:16 min
[INFO] Finished at: 2017-04-27T14:53:43-07:00
[INFO] Final Memory: 46M/410M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spark-network-shuffle_2.11: Could not resolve dependencies for project org.apache.spark:spark-network-shuffle_2.11:jar:2.1.0-k8s-0.1.0-SNAPSHOT: Could not find artifact org.apache.spark:spark-network-common_2.11:jar:tests:2.1.0-k8s-0.1.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
```

**Comment by erikerlandson** [comment]
@foxish any idea what I'm missing?

**Comment by erikerlandson** [comment]
The distro build appeared to complete successfully:

`% dev/make-distribution.sh --tgz -Phadoop-2.7 -Pkubernetes`

**Comment by foxish** [comment]
How does `./build/mvn package -Pkubernetes -DskipTests` work? I'm not sure why the compile step is failing. I'll test it out later today. @mccheah thoughts?

**Comment by foxish** [comment]
I'd omit the `-pl resource-managers/kubernetes/core` because I've had issues with that. It might be the reason why other parts aren't getting compiled.

**Comment by erikerlandson** [comment]
Weirdly, even the "compile" target isn't working for me, it had to be "package"

I proposed an edit to just use the "package" target for the example: #254

**Comment by erikerlandson** [comment]
This was merged, closing.
