### ISSUE TITLE
Proposal: Add spark parameter for driver pod name

### ISSUE THREAD

**Issue by hustcat** [apache-spark-on-k8s/spark#252]
Now the driver pod name is [spark.app.name-timestamp](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/kubernetes/submit/v1/Client.scala#L53) format, this is not flexible enough. We should add spark parameter for driver pod name, such as:

```
--conf spark.kubernetes.driver.pod.name=example-app
```

**Comment by ash211** [comment]
Fixed in linked PR
