### ISSUE TITLE
Support custom labels for the driver pod

### ISSUE THREAD

**Issue by mccheah** [apache-spark-on-k8s/spark#26]
One example use case is the driver pod also serves content, and the user who submits the driver wants to expose that content as a service. Instead of needing to worry about what labels spark-submit will choose, they can just provide their own labels (on top of the ones Spark generates) and have the service look for pods with said custom labels.

**Comment by foxish** [comment]
+1. This is a good idea.

**Comment by mccheah** [comment]
I'm not sure if executor labels will be as useful, however. That wouldn't be hard to add though.

**Comment by mccheah** [comment]
Done
