### ISSUE TITLE
Documentation plan for Spark

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#262]
As discussed in the SIG meeting earlier today, we need documentation coverage which is much more comprehensive to ensure that people have a good kick-the-tyres experience when using Spark on Kubernetes.
This will especially be a concern after our documentation change goes live.

Various broad categories of items that come to mind:
- [x] High level overview of Kubernetes as a cluster scheduler backend for Spark
- [ ] Running a SparkJob from the beta release
   - [x] Explaining various commandline options (mostly similar to [this](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/docs/running-on-kubernetes.md))
    - [x]  Cloud provider specific instructions
       - ~~[ ] Firewall rules and setup on GKE, AWS etc (https://github.com/apache-spark-on-k8s/spark/issues/245)~~
       - [x] GKE instructions
    - [x] On-premise deployments
    - [ ] Setting up a shuffle service DaemonSet
    - [ ] Setting up a submission server
- [x] Workflow
   - [x] Building custom images for drivers and executors
   - [x] Using the file submission server and local submissions
   - [x] Using an external storage mechanism (File Server/S3/GCS/external HDFS cluster)
- [x]  Running a development build
  - [x] Developer workflow 
  - [x] Integration tests
- [x] Debugging a SparkJob
  - [x] Using `kubectl` to identify memory, disk or other issues causing failure
  - [x] Using the Spark UI and dashboard
- [x] Best Practices and FAQ
- [x] Reporting issues and submitting PRs

Thoughts on any items we've missed? I expect that each of the top-level items will be pages of their own.
cc @apache-spark-on-k8s/contributors

**Comment by tnachen** [comment]
I don't know if adding using the Spark UI is anything K8s specific, is this planning to be added into the Spark documentation or a standalone docs site somewhere?

**Comment by kimoonkim** [comment]
> I don't know if adding using the Spark UI is anything K8s specific

Mostly no. But, in K8s, one needs to expose the driver UI port as `nodePort` using a config key.

**Comment by foxish** [comment]
Any thoughts on how we should present this documentation? IMO, the markdown files are getting pretty unwieldy, and we should either be generating html documentation from them, or creating html docs. 
cc @ash211

**Comment by ash211** [comment]
@foxish probably can close this now that we have docs up on the separate repo and a fair amount of investment made in them?
