### ISSUE TITLE
Confirm that spark submissions can run without V2 file staging

### ISSUE THREAD

**Issue by erikerlandson** [apache-spark-on-k8s/spark#271]
@mccheah may already be able to confirm this, but I'd like to ensure that spark jobs can (if desired) be submitted _without_ running a V2 file staging server (or V1, although that is being deprecated).

Obviously, running without file staging implies that the user is taking responsibility for ensuring that jars and data are accessible to Spark as URIs, or loaded onto their images.  But it should be an option.

**Comment by mccheah** [comment]
There's a few integration tests for this: https://github.com/apache-spark-on-k8s/spark/pull/251/files#diff-ed4818d5796b3e5486baa2f0abfdba07R94

**Comment by erikerlandson** [comment]
Thanks @mccheah!
