### ISSUE TITLE
Remove V1 Submission and replace with V2 only

### ISSUE THREAD

**Issue by mccheah** [apache-spark-on-k8s/spark#285]
Currently we have been developing the V2 submission logic in separate files so that we could build the feature incrementally. Now that we've built everything in version 2 of submission that was available to us in version 1 of submission, we should remove all of the v1 submission code and make spark-submit use version 2 of the submission.

This involves:
1. Change [this line](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L622) in SparkSubmit to point to the v2 submission client class,
2. Remove all code paths for v1 submission,
3. Remove the v1 driver docker file from our repository and publish the driver docker image as corresponding to [this Dockerfile](https://github.com/apache-spark-on-k8s/spark/blob/branch-2.1-kubernetes/resource-managers/kubernetes/docker-minimal-bundle/src/main/docker/driver-v2/Dockerfile),
4. Rewrite all the documentation so that the instructions are for submission with the new logic.

**Comment by erikerlandson** [comment]
If we want to enable some quick-and-dirty early testing, can the new "V2" parameters get a fast writeup on this issue?

**Comment by mccheah** [comment]
This is done.
