### ISSUE TITLE
Clean up shuffle files after completion of job

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#287]
The plan here is to use [subpath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) and a mechanism to register the driver with the shuffle service. The shuffle service would create the subdirectories for a specific SparkJob.

**Comment by erikerlandson** [comment]
@foxish what kind of registration mechanism do you have in mind?

**Comment by foxish** [comment]
Similar to that used in https://github.com/apache/spark/blob/master/resource-managers/mesos/src/main/scala/org/apache/spark/deploy/mesos/MesosExternalShuffleService.scala

I just prototyped a hostPath & subPath mechanism in k8s and will try and fit it into the above.

**Comment by foxish** [comment]
My thought for doing the actual clean-up is the [pre-stop hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-delivery-guarantees) which should let us execute an arbitrary cleanup script. The only part that our external shuffle service really needs to do, is to create a subdirectory for the shuffle files of each job. 

Once the subdirectory is created, we use the [`subpath`](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) to mount only the relevant sub-directory into each driver and associated executors.  

@mccheah @ash211 @lins05 Does this sound reasonable to you guys?
