### ISSUE TITLE
Fewer layers in docker images

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#323]
https://github.com/apache-spark-on-k8s/spark/pull/320#issuecomment-305323096

Basically, don't repeatedly use RUN

**Comment by johscheuer** [comment]
Hi, I stumbled over this issue (I want to learn more about Spark on Kubernetes) and wanted to fix this issue. After I looked into the Dockerfiles I found out that there are many repetitions in the Docker images maybe it would be a good move to create a `base-image` ?

**Comment by mccheah** [comment]
Using a base image would be helpful - can you push something for review? `SparkDockerImageBuilder` would need changes as well.

**Comment by ash211** [comment]
@johscheuer thanks for taking an interest in this project!

We can do this by merging the RUN commands in each separate Dockerfile, and then later creating a `base-image`, or jumping straight to creating the base image.

If you're interested in contributing to this project with a PR I'd be happy to help code review!
