### ISSUE TITLE
Apply spark.app.name and spark.app.id as labels to the created pods

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#33]
Automatically add `spark.app.name` and `spark.app.id` as labels to pods.  This makes selecting pods by an ID easier.  See https://github.com/apache-spark-on-k8s/spark/pull/32#issuecomment-273654470

Also note that this follows a similar pattern as other k8s controllers like Job: https://kubernetes.io/docs/user-guide/jobs/#running-an-example-job

**Comment by mccheah** [comment]
Added it for `spark.app.name` to #23 as an incidental fix to the integration tests.

Edit: Ah, this only adds the label for the driver - have yet to fix the executors.

**Comment by foxish** [comment]
This is done, closing.
