### ISSUE TITLE
Rebase onto Apache Spark 2.2.0

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#345]
When it's released (in RC voting as of Jun 14)

Known things we'll need to accommodate:
- `ExternalShuffleClient` constructor [changed](https://github.com/apache/spark/commit/8f3f73abc1fe62496722476460c174af0250e3fe#diff-b5e8b9a95773c9bdab767b8979192f6aR62) (cc @foxish)
- `TransportClientFactory.createClient()` now throws an [additional checked exception](https://github.com/apache/spark/commit/1c4d10b10c78d138b55e381ec6828e04fef70d6f#diff-609024dc2bd224d45a6c57582490d995R126) (cc @foxish)

**Comment by ash211** [comment]
Please ping me when doing the migration, I have a commit that accommodates these two Spark-internal API breaks

**Comment by ash211** [comment]
From today's weekly sync, @foxish plans to begin this this week, and do a final release off branch-2.1-kubernetes.

**Comment by foxish** [comment]
This is done.
