### ISSUE TITLE
Support for Spark Web UI

### ISSUE THREAD

**Issue by duyanghao** [apache-spark-on-k8s/spark#353]
@mccheah In my tests,i have not found spark.ui.port(404x) in driver.
Does the spark on k8s support Spark Web UI as the native spark does? And how to do if it does?

**Comment by foxish** [comment]
It is possible to get to the driver UI after running `kubectl proxy` using:

`http://localhost:8080/api/v1/namespaces/default/pods/<driver_pod_name>:4040/proxy`
by replacing `<driver_pod_name>` with the name of the driver pod. 
There is an existing bug here, https://github.com/apache-spark-on-k8s/spark/issues/304 and deploying a fix similar to https://github.com/apache-spark-on-k8s/spark/issues/87 should get the executors tab also working again.

**Comment by foxish** [comment]
It is future work to use CRDs (formerly TPRs), and have a better and more convenient way of surfacing the URL to the user.

**Comment by duyanghao** [comment]
@foxish From my tests,we can only get driver UI of running tasks.Is there any way to get driver UI of finished tasks?

**Comment by tnachen** [comment]
@duyanghao Spark itself doesn't support this, the only way to see finished task's history is from Spark History server.

**Comment by duyanghao** [comment]
@tnachen i will try to use spark history server,but don't know whether the configuration is the same with [native spark](https://spark.apache.org/docs/2.1.0/monitoring.html).

**Comment by mccheah** [comment]
The configuration should more or less be identical - as long as the history server is reading from the same event log directory as the Spark applications are writing to. You'll need some shared distribution storage layer like HDFS or S3, but this situation is no different to the standard usage of the Spark History Server right now.

**Comment by mccheah** [comment]
However if your HDFS is only accessible in your Kubernetes cluster then you'll need to deploy the Spark History Server with Kubernetes as well. You'll need to build a Docker image that runs the history server and create a Kubernetes resource spec that you send to your API server.

**Comment by duyanghao** [comment]
@mccheah thanks, there are still many problems for loading large eventlog file when spark history server runs,but this is nothing to do with this project,i will close the issue.
