### ISSUE TITLE
User-specified node selector on pods

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#358]
I'd like to be able to add a Spark configuration to specify a node selector for all pods in the Spark job.  This helps me select all pods from the job to do e.g. resource tracking per job.

**Comment by mccheah** [comment]
This continues to build on the need for custom pod specifications as mentioned in #38. I suppose the feature set and room for customization is possibly greater in Kubernetes compared to all of the other cluster managers that are supported so far. The original design that aligns with the other cluster managers may be too limiting here.

**Comment by mccheah** [comment]
Oh I think this is handled by #355
