### ISSUE TITLE
spark.executor.instances par seems invalid when it is large

### ISSUE THREAD

**Issue by duyanghao** [apache-spark-on-k8s/spark#368]
@mccheah When i set submit pars as below:
```
--conf spark.driver.memory=3G \
--conf spark.driver.cores=2 \
--conf spark.executor.instances=100 \
--conf spark.executor.memory=3G \
--conf spark.executor.cores=2 \
```
the spark task has been created successfully,but the problem is that only 50 executors has been produced during the whole life of the spark task(which keeps running all the time, never stopping)

so, i guess whether the spark.executor.instances par will become invalid when it is large?

**Comment by ash211** [comment]
@duyanghao possibly your cluster doesn't have enough space for 100 executor instances?  I would expect the current version of Spark to launch 100 executors and block until they're all ready, then begin launching tasks on the executors.

**Comment by duyanghao** [comment]
@ash211 I can make sure there are enough resources for this task to run!
Have you tested the scenario for more than 100 spark.executors?

**Comment by ash211** [comment]
I haven't personally tested >100 executors but am currently unaware of any limits that would cause this to fail.

Are the pods not getting submitted and visible in `kubectl`, or are they not getting scheduled (stuck in pending state) ?

**Comment by duyanghao** [comment]
@ash211 another 50 pods are not visible  in `kubectl` as below:
```
kubectl get pods -n=xxx -a|grep app-kafka-streaming-1499486419238296266|wc -l
50
```

Addition: all pods created by this submit named by `app-kafka-streaming-1499486419238296266`

**Comment by ash211** [comment]
Can you please attach the logs from the spark-submit call in a `.txt` file here or on a pastebin-style website?

**Comment by duyanghao** [comment]
@ash211 @mccheah seen from the k8s log,there are only created records of `app-kafka-streaming-1499486419238296266-(1-50)` pods, nothing about `51-100` executor pods appears.

**Comment by duyanghao** [comment]
@ash211 @mccheah It's strange enough that another task test show that it could produce 100 executors,maybe there is some unknown internal adjustments of driver for producing how many executors to run spark task.

So,i guess the driver doesn't decide produced executor nums only by par `spark.executor.instances`.Maybe there are some other influencing factors, such as the workload of spark task.

**Comment by erikerlandson** [comment]
@duyanghao the spark driver log output will be very informative for localizing what is happening

**Comment by duyanghao** [comment]
@erikerlandson Here are the last few lines for `Requesting a new executor` in driver logs:
```
[2017-08-10 12:52:14,077] INFO Requesting a new executor, total executors is now 47 (org.apache.spark.scheduler.cluster.kubernetes.Kube
rnetesClusterSchedulerBackend)
[2017-08-10 12:52:14,088] INFO Requesting a new executor, total executors is now 48 (org.apache.spark.scheduler.cluster.kubernetes.Kube
rnetesClusterSchedulerBackend)
[2017-08-10 12:52:14,097] INFO Requesting a new executor, total executors is now 49 (org.apache.spark.scheduler.cluster.kubernetes.Kube
rnetesClusterSchedulerBackend)
[2017-08-10 12:52:14,106] INFO Requesting a new executor, total executors is now 50 (org.apache.spark.scheduler.cluster.kubernetes.Kube
rnetesClusterSchedulerBackend)
```
@ash211 @mccheah @erikerlandson Can any one give some suggestions?

**Comment by erikerlandson** [comment]
@duyanghao spark's dynamic allocation logic will never request more executors than there are data partitions.  So one possibility is; if there are 50 partitions in the data, then that will be the maximum the driver requests.

**Comment by duyanghao** [comment]
@erikerlandson i didn't enable `spark's dynamic allocation`.

seen from `kube-scheduler.ERROR` log:

```
factory.go:583] Error scheduling xxx app-kafka-streaming-1499486419238296266-exec-50: pod (app-kafka-streaming-1499486419238296266-exec-50) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (2); retrying
...
```

there are not enough resources to allocate.

but still  `allocatorRunnable` should deal with this situation and report some errors when fail to create executor pods.

**Comment by duyanghao** [comment]
@ash211 @erikerlandson i will close this issue since at the moment there is no better way to handle this situation than by avoiding it.
