### ISSUE TITLE
How to set spark.docker.test.persistMinikube when running the integration tests?

### ISSUE THREAD

**Issue by lins05** [apache-spark-on-k8s/spark#37]
When I run the k8s integration tests, the property `spark.docker.test.persistMinikube` seems not respected.

```sh
build/mvn -Pkubernetes -Pkubernetes-integration-tests \
          -pl resource-managers/kubernetes/integration-tests  \
          -Dtest=xxx -DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite \
          -Dspark.docker.test.persistMinikube=true \
          integration-test -am
```

But the minikube cluster is always deleted after the tests.

I also tried to run the tests with sbt, but since we haven't added sbt support for k8s modules, currently the command below doesn't work yet:

```
./build/sbt -Pkubernetes -Pkubernetes-integration-tests \
    -Dspark.docker.test.persistMinikube=true \
    "kubernetes-integration-tests/test-only org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite"
```

**Comment by mccheah** [comment]
What are you doing to verify that the cluster is torn down?

**Comment by lins05** [comment]
@mccheah I see log messages like these:

```
17/01/23 07:11:44 INFO Minikube: 192.168.99.100
17/01/23 07:11:48 INFO Minikube: 192.168.99.100
17/01/23 07:13:52 INFO Minikube: minikubeVM: Running
17/01/23 07:13:52 INFO Minikube: localkube: Running
17/01/23 07:13:55 INFO Minikube: Deleting local Kubernetes cluster...
17/01/23 07:13:56 INFO Minikube: Machine deleted.
```

And `minikube status` also shows that the VM doesn't exist.

**Comment by mccheah** [comment]
Hm, from this [stackoverflow post](https://stackoverflow.com/questions/824019/maven-2-1-0-not-passing-on-system-properties-to-java-virtual-machine) it's possible that passing system properties via -D doesn't propagate the property to the test. The test is run in a forked JVM and it doesn't inherit the system properties from the Maven process.

Looks like we can try setting `-DforkMode=never` or `-DargLine="-Dspark.docker.test.persistMinikube=true"`.

**Comment by mccheah** [comment]
Filed #39 to track the sbt build.

**Comment by ssuchter** [comment]
How does the forked JVM run? Is it coming from a particular maven plugin?

**Comment by mccheah** [comment]
Don't know offhand, think it's the surefire plugin though so there may be something there.

**Comment by ssuchter** [comment]
Is there a patch or command line you are using that I can try to use? Or is
this coming from some file in the tests dir? If I can see how it’s invoked
within Maven, I can probably suggest the way to pass the options.

Sean

On January 25, 2017 at 3:12:52 PM, mccheah (notifications@github.com) wrote:

Don't know offhand, think it's the surefire plugin though so there may be
something there.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark/issues/37#issuecomment-275262638>,
or mute the thread

**Comment by mccheah** [comment]
@lins05 posted what he tried above, and it results in the Minikube VM still being deleted in the `afterAll` block.

**Comment by lins05** [comment]
> Looks like we can try setting -DforkMode=never or -DargLine="-Dspark.docker.test.persistMinikube=true".

I tried `argLine` but it didn't work. I guess it's because `argLine` is already set in spark's top level pom.xml: https://github.com/apache/spark/blob/v2.1.0/pom.xml#L2055 so it's not possible to overwrite it from command line.

Using `-DforkMode=never` would cause a different error:

```
  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite
```

**Comment by lins05** [comment]
Please see https://github.com/apache-spark-on-k8s/spark/pull/52 for a possible solution.

**Comment by mccheah** [comment]
Did #52 resolve it? Can we close this?

**Comment by lins05** [comment]
Right, let's close it.
