### ISSUE TITLE
[Question] why design a resource stage server

### ISSUE THREAD

**Issue by FANNG1** [apache-spark-on-k8s/spark#371]
spark-on-yarn uses HDFS to store app dependencys, why spark-on-k8s use a  resource stage server not HDFS?
there may be some problem about resource stage server:
1, single point, if restarted or migrated the resource may lost
2, if many jobs concurrently uploading/downloading resources, the performence is likely poor(not tested yet)

**Comment by ash211** [comment]
Not all spark-on-k8s users are running HDFS in k8s.  In YARN there's a dependency on HDFS so YARN applications can assume that an HDFS exists.  But in k8s there's no HDFS dependency, and no other feature of k8s for stateful storage exist.  So for Spark had to make something ourselves.

**Comment by mccheah** [comment]
Kubernetes and YARN differ in the sense that YARN is tightly coupled with the Hadoop ecosystem where Kubernetes is not. Allowing Kubernetes applications to be launched without HDFS allows for more flexibility for users who wish to avoid having to stand up an entire distributed system just to run one-off applications. The user may use a different distributed storage medium for their industry’s data that isn’t suitable for mounting dependencies, such as a storage layer that is massive but only eventually consistent. In this case, it is much easier for a user to deploy a single HTTP service than it is for them to consider the provisioning of an entire distributed storage backend.

This matter is further reinforced when we consider that Mesos does not allow users to submit using local files at all. In mesos-cluster mode, all dependencies have to be pre-staged over some remote storage layer like HDFS or HTTP.

The resource staging server is also only a strictly optional component. Application writers can choose to pre-stage their dependencies in a different storage layer like HDFS or HTTP. We expect a very common use case to be having the application writers mount their dependencies into the Docker images to allow these dependencies to be cached.

**Comment by FANNG1** [comment]
thx, so HDFS maybe an optional backend for stage server ?

**Comment by ash211** [comment]
Yeah, I could see that.  Preferable to both HDFS and staging server though is to bake the necessary jars right into the docker image you're running -- then they're cached on each node by dockerd
