### ISSUE TITLE
Cutting a new Spark 2.1 release

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#416]
This is a prerequisite to announcing upstream.

Steps:

1. [x] Build a distribution with and without hadoop
2. [x] Tag the commit, draft a github release, and upload the tar.gz files in (1)
3. [x] Build and upload the images (appropriately tagged) to the kubespark repo
4. [x] Fill in the release description on GitHub 

@apache-spark-on-k8s/contributors 

"blocking" PRs:

1. [x] https://github.com/apache-spark-on-k8s/spark/pull/422
1. [x] https://github.com/apache-spark-on-k8s/spark/pull/415
1. [x] https://github.com/apache-spark-on-k8s/spark/pull/412

**Comment by kimoonkim** [comment]
Maybe we also want the bug fix #412, which seems almost ready to merge? The bug may impact many large jobs even when they don't use HDFS.

**Comment by foxish** [comment]
You mean https://github.com/apache-spark-on-k8s/spark/pull/412? Yeah, I think that's a good one to include as well!

**Comment by kimoonkim** [comment]
Correct. #412.

**Comment by foxish** [comment]
PSA: Need an owner from the community for cutting this release. @erikerlandson is doing the 2.2 one, any volunteers for this? @apache-spark-on-k8s/contributors

**Comment by liyinan926** [comment]
@foxish I can help on cutting a new 2.1 release.

**Comment by liyinan926** [comment]
@foxish I don't seem to have permission to create a release.

**Comment by liyinan926** [comment]
Still need to build and upload the new images.

**Comment by liyinan926** [comment]
Published all images tagged with `v2.1.0-kubernetes-0.3.1`.
