### ISSUE TITLE
Looking for a way to run only the kube unit/integration testing

### ISSUE THREAD

**Issue by erikerlandson** [apache-spark-on-k8s/spark#426]
By default, running the documented command ...

```sh
build/mvn integration-test \
    -Pkubernetes -Pkubernetes-integration-tests \
    -pl resource-managers/kubernetes/integration-tests -am
```

... runs all of spark's testing.  This not only takes forever, but required me to reconfigure my allowed number of open file-descriptors (`ExecutorAllocationManagerSuite` seems to be the main culprit here).

If there is already an easy way to do this from the maven CLI, I can't find it.  If there isn't, I'm wondering if somebody who is more conversant with maven knows how to reconfigure the poms to make this easier.

**Comment by erikerlandson** [comment]
cc @foxish @mccheah

**Comment by ssuchter** [comment]
Is your question how to skip spark’s testing or how to change the allowed
number of open file-descriptors from maven?

**Comment by erikerlandson** [comment]
skip spark's testing.  conversely, run only the kube related testing

**Comment by erikerlandson** [comment]
Hmm, looking at the CI console output, maybe it's this:

`-Dtest=none -DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite`

**Comment by ssuchter** [comment]
I was just looking into something like that. That feels right…

Sean

On August 11, 2017 at 3:50:22 PM, Erik Erlandson (notifications@github.com)
wrote:

Hmm, looking at the CI console output, maybe it's this:

-Dtest=none
-DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/apache-spark-on-k8s/spark/issues/426#issuecomment-321935462>,
or mute the thread

**Comment by kimoonkim** [comment]
Yes, I believe we did that in Jenkins exactly for that purpose.

**Comment by ifilonenko** [comment]
```
build/mvn clean pre-integration-test -T 4C -Pkubernetes -Pkubernetes-integration-tests -pl resource-managers/kubernetes/integration-tests -am -DskipTests
```
```
build/mvn -B clean integration-test -Pkubernetes -Pkubernetes-integration-tests -pl resource-managers/kubernetes/integration-tests -am -DextraScalaTestArgs=-Dspark.docker.test.persistMinikube=true -Dtest=none -DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite
```

**Comment by erikerlandson** [comment]
This seems to work, at least for the IT since it is only one test class.  Unit tests would need some kind of regular expression `.*kubernetes.*`
Anyway, I can close this
