### ISSUE TITLE
SPIP: Spark on Kubernetes

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#435]
We sent an [SPIP](https://spark.apache.org/improvement-proposals.html) up to the spark community here.
http://apache-spark-developers-list.1001551.n3.nabble.com/SPIP-Spark-on-Kubernetes-td22147.html

I was made aware that it would help the community understand the importance of this change if some of us could explain our use of it, 
and the reason(s) why we want Spark to support this change.

cc/ @sandflee @duyanghao @weiting-chen @luck02 @matyix @dansanduleac @apache-spark-on-k8s/contributors

**Comment by luck02** [comment]
I can document our requirements and what we're moving to.  Send to user/dev spark?

**Comment by foxish** [comment]
Yes, the dev mailing list, as a response to the spip post that I linked to
above.

**Comment by foxish** [comment]
This has passed.
