### ISSUE TITLE
How to kill a running spark job?

### ISSUE THREAD

**Issue by leletan** [apache-spark-on-k8s/spark#436]
On a standalone cluster we used to kill a running spark job by submission_id, which I am not sure if supported here. Or any work around to achieve the same thing?

**Comment by mccheah** [comment]
Use `kubectl` to delete the driver pod and that should also delete all of the objects the application depends on.

**Comment by leletan** [comment]
Thanks.

**Comment by mccheah** [comment]
In the future when we have a Spark CustomResource we should theoretically be able to use the Kubernetes dashboard to destroy Spark applications.
