### ISSUE TITLE
no log links in spark history server(spark on k8s)

### ISSUE THREAD

**Issue by duyanghao** [apache-spark-on-k8s/spark#443]
Seen from `spark history server` of `spark on yarn`,it gives driver and executors log links,and each log has four types: `gc.log`,`spark.log`,`stderr`,`stdout`.But there is no link about log from `spark history server`(`spark on k8s`)

Although i am unfamiliar with the `spark history server`,but it's a strange phenomenon.

@erikerlandson any suggestions?

**Comment by foxish** [comment]
Are you running a spark history server deployment? What does your spec look like?

**Comment by duyanghao** [comment]
@foxish i start SHS using `./sbin/start-history-server.sh` of `spark-2.1.0-k8s-0.1.0-SNAPSHOT-bin-2.2.0`(build from [`branch-2.1-kubernetes`](https://github.com/apache-spark-on-k8s/spark/tree/branch-2.1-kubernetes) branch).

**Comment by foxish** [comment]
That wouldn't work, unless that's running within the cluster. We need to write a deployment that launches the SHS within the cluster. Tracked in https://github.com/apache-spark-on-k8s/spark/issues/387. Closing as dupe.
