### ISSUE TITLE
update image tags in kubernetes-shuffle-service.yaml

### ISSUE THREAD

**Issue by erikerlandson** [apache-spark-on-k8s/spark#457]
they need to be updated to v2.2.0-kubernetes-0.3.0

**Comment by sahilprasad** [comment]
@erikerlandson would the spark-version label need to be updated to 2.2.0 as well?

**Comment by erikerlandson** [comment]
@sahilprasad yes it should also be 2.2.0

**Comment by sahilprasad** [comment]
@erikerlandson this also applies to conf/kubernetes-resource-staging-server.yaml

**Comment by erikerlandson** [comment]
closing with merge of #460
