### ISSUE TITLE
Pull kubernetes config keys out into a separate class

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#47]
Something like the below class for kubernetes would be good for making sure we're not missing config keys in the docs, plus generally pull all config keys into one place which seems like a good idea.

https://github.com/apache/spark/blob/v2.1.0/yarn/src/main/scala/org/apache/spark/deploy/yarn/config.scala

**Comment by mccheah** [comment]
+1 - I'll take ahold of this, primarily because `Client.scala` is getting a little cumbersome to read.
