### ISSUE TITLE
Unit tests in SparkSubmitSuite

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#495]
https://github.com/apache-spark-on-k8s/spark/blob/branch-2.2-kubernetes/core/src/test/scala/org/apache/spark/deploy/SparkSubmitSuite.scala

**Comment by ifilonenko** [comment]
I'lll handle this one

**Comment by liyinan926** [comment]
Closing this as this is done and the changes have been upstreamed.
