### ISSUE TITLE
Cut a new Spark-Kubernetes 2.2 release

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#499]
Prerequisites:

1. [x] Finish the rename (https://github.com/apache-spark-on-k8s/spark/pull/497)
2. [x] Remove deprecated configuration now (https://github.com/apache-spark-on-k8s/spark/pull/501)
3. [x] Update RBAC documentation (https://github.com/apache-spark-on-k8s/spark/issues/500)
1. [x] Update poms for 2.2 release 0.4.0 (https://github.com/apache-spark-on-k8s/spark/pull/508)

Post release:

1. [x] Update documentation to point to 2.2 docker images. (currently points at 2.1) (https://github.com/apache-spark-on-k8s/userdocs/issues/15)

cc @mccheah @ash211 @erikerlandson @apache-spark-on-k8s/contributors

**Comment by ifilonenko** [comment]
SparkR support into this new release, as we push upstream?

**Comment by foxish** [comment]
I think it would be the next one.  These are pretty separate and a release
is long overdue. The plan was to cut the release today - was doing some
manual testing. Should be able to tag the branch and start merging other
stuff in right after.

**Comment by liyinan926** [comment]
Built and pushed all v2.2.0-0.4.0 images. Pending tests. It would be great if folks can run some tests against them.

**Comment by erikerlandson** [comment]
Any potential concerns that @liyinan926 images built differently than @foxish build script?

**Comment by liyinan926** [comment]
I just tried using the script to build and push. The images should be good.

**Comment by liyinan926** [comment]
New release published at https://github.com/apache-spark-on-k8s/spark/releases/tag/v2.2.0-kubernetes-0.4.0.

**Comment by erikerlandson** [comment]
@liyinan926 for posterity can you post the build commands you used here.  The ones I used to cut the previous release are [here](https://github.com/apache-spark-on-k8s/spark/issues/438#issuecomment-322915358)

**Comment by liyinan926** [comment]
Sure, the commands I used are:
```
./dev/make-distribution.sh --pip --tgz -Pmesos -Pyarn -Pkinesis-asl -Phive -Phive-thriftserver -Pkubernetes -Phadoop-2.7 -Dhadoop.version=2.7.3
./dev/make-distribution.sh --pip --tgz -Pmesos -Pyarn -Pkinesis-asl -Phive -Phive-thriftserver -Pkubernetes -Phadoop-2.7 -Dhadoop.version=2.7.3 -Phadoop-provided
```

**Comment by erikerlandson** [comment]
Published the release announcement to spark dev and user lists
