### ISSUE TITLE
Update integration testing to match new package name k8s

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#509]
From https://github.com/apache-spark-on-k8s/spark/pull/497#issuecomment-331751032

> @varunkatta @ssuchter The Jenkins environment needs to be updated since the commands had a wildcard on deploy.kubernetes.* which has been changed to deploy.k8s.*

cc/ @ifilonenko

**Comment by foxish** [comment]
@ifilonenko, only the integration tests need the update as far as I checked. Correct?

**Comment by ifilonenko** [comment]
Unit tests don't have wildcard because they run complete unit tests, so yes, I believe so

**Comment by ssuchter** [comment]
I think this is done. I modified two command lines in these builds:

PR-spark-k8s-integration-test
SCHEDULED-spark-k8s-integration-test

and one command line in this build:

test-spark

**Comment by foxish** [comment]
Verified that this is fixed. Thanks @ssuchter!
