### ISSUE TITLE
Weekly meeting

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#55]
Since we've grown to having quite a few people contributing and wanting to contribute, I propose that we have a weekly meeting.
In the meeting, we can discuss what everyone is doing and the priorities as we move forward.

What do you guys think of a meeting weekly using hangouts/zoom?

/cc @ash211 @kimoonkim @mccheah @erikerlandson @ssuchter @iyanuobidele @lins05 @tnachen

**Comment by lins05** [comment]
+1

**Comment by mccheah** [comment]
Sounds great to me.

**Comment by ash211** [comment]
Sounds great, I'd love to participate in a weekly.  @foxish can you take setting it up?

**Comment by erikerlandson** [comment]
Works for me.  SIG-bigdata seems appropriate.  I actually presented this work for SIG-apps, so that could be another SIG option.

**Comment by foxish** [comment]
I created a doodle here to decide on **days** and times that work for all. http://doodle.com/poll/u9ipc33vttrs8wrt
Please ignore the dates.

**Comment by kimoonkim** [comment]
Sounds good to me. Thanks for setting this up!

**Comment by prb** [comment]
I'd like to join as well and bring a colleague; added myself to the Doodle.

**Comment by foxish** [comment]
Thanks for filling the doodle out. I think we've converged on 10am PT on Wed/Fri. I am leaning towards Wednesday for sig-big-data, and will be proposing that time (unless someone has an objection). I'll send out invites once we have the sig setup.

**Comment by iyanuobidele** [comment]
Wednesday SGTM. Thanks for taking that on!

**Comment by ash211** [comment]
Thanks @foxish for organizing!  I'd like to start putting things on a meeting agenda for next week's discussion.  How would you like to coordinate that?  A group-editable google doc?

**Comment by foxish** [comment]
I started a [thread](https://groups.google.com/forum/#!topic/kubernetes-dev/1FACSVsWEp8) about sig-big-data and will watch till Monday to see if there are any objections. 
On Monday, I'll go through the sig creation procedures and we can start using https://groups.google.com/forum/#!forum/kubernetes-sig-big-data. 
A shared doc for agenda and notes sounds good. The old SIG-big-data used https://docs.google.com/document/d/1YhNLN39f5oZ4AHn_g7vBp0LQd7k37azL7FkWG8CEDrE/edit#.

**Comment by ssuchter** [comment]
Wednesday is good for me too, thanks. Are we starting on the 1st or the 8th? (I didn't see anything in kubernetes-sig-big-data, but is that the right place to look?) Thanks Anirudh!

**Comment by foxish** [comment]
@ssuchter We'll meet this Wednesday (1st). 
I'm still setting up the groups, will send out a zoom link shortly. 
The slack channel can now be used as well https://kubernetes.slack.com/messages/sig-big-data/

**Comment by foxish** [comment]
@ash211 

The hangouts URL for tomorrow's meeting is https://hangouts.google.com/call/t3ylt5b5hfbfhjka7xcuve4dlqe
The doc where we can put in the meeting notes and agenda every week is https://docs.google.com/document/u/1/d/1pnF38NF6N5eM8DlK088XUW85Vms4V2uTsGZvSp8MNIA/edit

**Comment by foxish** [comment]
Closing this now.
The meeting URL going forward is https://zoom.us/my/sig.big.data
