### ISSUE TITLE
Does this one have a spark UI?

### ISSUE THREAD

**Issue by leletan** [apache-spark-on-k8s/spark#563]
It seems the kubernetes dashboard has very limited information about the spark jobs, compared to what spark standalone can provide. Is there such a thing for spark-on-kube?

**Comment by liyinan926** [comment]
You can access the Spark web UI using port forwarding. See https://github.com/apache-spark-on-k8s/spark/blob/e2e6fb08414656c6c39efda92fbbce804f93dd59/docs/running-on-kubernetes.md#accessing-driver-ui.

**Comment by leletan** [comment]
Thanks this is really helpful.

**Comment by liyinan926** [comment]
Interesting. This should work as port forwarding is a native Kubernetes feature.

**Comment by leletan** [comment]
Sorry my bad, this is working.
