### ISSUE TITLE
Create NodePort service from within driver pod

### ISSUE THREAD

**Issue by foxish** [apache-spark-on-k8s/spark#57]
We want to delay the service creation to do it within driver code, so that we don't use up NodePorts when the driver pod is still pending.
One caveat is that there is a time delay between creation of the service and to when kube-proxy opens up the requisite ports on the nodes. We would want to ensure that we have the necessary retry/waiting logic as well.

**Comment by ash211** [comment]
@foxish is this to minimize the amount of time in which a service exists but is not in use?

Can you create a watch on a service that doesn't yet exist?  If so that could serve as the triggering mechanism connecting driver ready with service exposed -> spark-submit should upload jars and config.

**Comment by mccheah** [comment]
This would require the `KubernetesSparkRestServer` to create the service and for the REST Server to agree with the Client on the labels the service is going to have. I'm uncertain if the upside for reducing the amount of time the NodePort is alive is worth the complexity we introduce here. Currently the `KubernetesSparkRestServer` does not have any interaction with Kubernetes at all, and it would be nice to keep the REST server as simple as possible, and to keep the lifecycle of the required K8s components in as few places as possible.

We only create the NodePort service after the driver container has started running, as the driver pod Watch listens for the container to begin running before it builds the service. Is there any reason to believe that the delay would be significant?

**Comment by foxish** [comment]
> We only create the NodePort service after the driver container has started running, as the driver pod Watch listens for the container to begin running before it builds the service.

Ah. I haven't seen the Nodeport PR in detail yet and my issue was based on the old behavior which creates the service before creating the pod. Closing this issue.
