### ISSUE TITLE
Mount volumes on driver pod?

### ISSUE THREAD

**Issue by hochuenw** [apache-spark-on-k8s/spark#630]
I am doing this because I want to store the output back to my local file system since in the cluster mode, the output is written back the driver pod. Is this supported?

**Comment by mccheah** [comment]
I'm pretty sure we will support volume mounts but only on Spark 2.4. You can also take the tip of the master branch of Spark to get volume support.

Also, please note that we are no longer improving this fork at all and all further development is being done towards apache/master.

**Comment by mccheah** [comment]
Actually volume support is in the works - https://github.com/apache/spark/pull/21260
