### ISSUE TITLE
decouple servlets from KubernetesSparkRestServer

### ISSUE THREAD

**Issue by iyanuobidele** [apache-spark-on-k8s/spark#64]
Reasons:
- aesthetic change to match other restServer implementations. 
See [standAloneRestServer](https://github.com/apache-spark-on-k8s/spark/blob/k8s-support-alternate-incremental/core/src/main/scala/org/apache/spark/deploy/rest/StandaloneRestServer.scala#L51)and [mesosRestServer](https://github.com/apache-spark-on-k8s/spark/blob/k8s-support-alternate-incremental/resource-managers/mesos/src/main/scala/org/apache/spark/deploy/rest/mesos/MesosRestServer.scala#L40).
- preparation for other servlet implementations

**Comment by iyanuobidele** [comment]
Is this a worthy change ? Thoughts ?

**Comment by mccheah** [comment]
Hm, what do we mean by decouple here? The other implementations seem to embed the servlet classes as nested classes to the server class also.

Anything to make the code neater is a good idea.

**Comment by iyanuobidele** [comment]
@mccheah 
Yes, that's true.

The current implementation in kubernetesSparkRestServer, has its servlets as inner classes and here's what i'm suggesting. 

`private class KubernetesSparkRestServer(...) {`
    `private val pingServlet = new PingServlet`
    `override protected val submitRequestServlet: SubmitRequestServlet = ...`
  `override protected val statusRequestServlet: StatusRequestServlet = ...`
  `override protected val killRequestServlet: KillRequestServlet = null`

`override protected lazy val contextToServlet = Map[String, RestServlet](`
    `s"$baseContext/create/*" -> submitRequestServlet,`
    `s"$baseContext/ping/*" -> pingServlet)`
`} // end of KubernetesSparkRestServer`

` private class PingServlet extends RestServlet {`
`......`
`}`


` private class KubernetesSubmitRequestServlet(.....) extends SubmitRequestServlet {`
`......`
`}`

.....

 I'm looking ahead to the implementation of the statusRequestServlet and other servlets. Also, this would match other implementations and separate the logics.

**Comment by mccheah** [comment]
Ah I see. Yes, this seems like a good idea.

**Comment by foxish** [comment]
@iyanuobidele, do we want to do this refactor for the alpha release?

**Comment by iyanuobidele** [comment]
I was looking to make this refactor in order to accommodate subsequent servlets. Since we won't be looking at those now and it's not a blocker, I'll label this beta.

**Comment by mccheah** [comment]
Closing this because we changed the server design.
