### ISSUE TITLE
The driver web ui's executors page can't load properly through kubectl proxy

### ISSUE THREAD

**Issue by lins05** [apache-spark-on-k8s/spark#87]
Current when visit the spark driver web ui, the executors page can't load properly.

E.g. When I access the executors page at http://localhost:8001/api/v1/proxy/namespaces/default/services/spark-pi-1486223713270:4040/executors/, the js would try to use ajax to load the executors info from http://localhost:8001/api/v1/proxy/namespaces/api/v1/applications/namespaces/allexecutors.

This is because some [special handling in the executors page's js](https://github.com/apache/spark/blob/v2.1.0/core/src/main/resources/org/apache/spark/ui/static/executorspage.js#L99) for the "proxy" keywords in the url for yarn applications.

**Comment by ash211** [comment]
Good catch -- looks like that code indeed assumes that if `proxy` is in its URL then it's running in YARN, which has proxy URLs that look like 

http://masternode:8088/proxy/application_1463264445515_0001/

However that doesn't work for k8s, which also has the word `/proxy/` in its path...  an unfortunate collision!

I think we can probably add another if block before the existing two using the search term `api/v1/proxy/namespaces` directly on the baseURI and return immediately if necessary (or do whatever changes).

@lins05 do you have bandwidth to take this one on?  Probably the trickiest part will be ensuring that we don't break the YARN UI in the process.

**Comment by lins05** [comment]
SGTM, I'll submit a patch this week.
